### ISSUE TITLE
its not working

### ISSUE THREAD

**Issue by TABREZ-96** [EdoardoPona/Ara#1]

**Comment by EdoardoPona** [comment]
Hello, 
Could you be more specific? What have you tried, and what happens?

**Comment by TABREZ-96** [comment]
<img width="960" alt="Ara" src="https://user-images.githubusercontent.com/114156392/204699451-1fe1d0cd-d51f-4877-9d57-d45852225de9.png">

**Comment by EdoardoPona** [comment]
Hello. `main.py` is to start the server, use script.py to run the program on some input you have. 
Check out commit 38cbe5e90c9ca0dfd83050f076dcf91c68824474 with instructions in the README
